### ISSUE TITLE
Fixed header logo

### ISSUE THREAD

**Issue by bobapple** [NETWAYS/pretix-email-net#3]
There's the requirement to use a fixed header logo in favour of loading the image that is configured in pretix. 

The following logo should be used: https://www.netways.de/wp-content/uploads/2021/07/202004_TrainingsLogo_white_600x200.png

**Comment by Corinari** [comment]
Should the logo be also a Hyperlink?

**Comment by bobapple** [comment]
Yep, logo should refer to https://www.netways.de/trainings/

**Comment by Corinari** [comment]
With 600x200, Logo was very grainy. Reduced to 300x200 (WxH). 
if suitable, please close
